/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()
const BybitLazyImport = createFileRoute('/bybit')()
const BinanceLazyImport = createFileRoute('/binance')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const BybitLazyRoute = BybitLazyImport.update({
  path: '/bybit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bybit.lazy').then((d) => d.Route))

const BinanceLazyRoute = BinanceLazyImport.update({
  path: '/binance',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/binance.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/binance': {
      preLoaderRoute: typeof BinanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/bybit': {
      preLoaderRoute: typeof BybitLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BinanceLazyRoute,
  BybitLazyRoute,
  SettingsLazyRoute,
])

/* prettier-ignore-end */
