/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SettingsSettingsLazyImport = createFileRoute('/settings/settings')()
const BybitBybitLazyImport = createFileRoute('/bybit/bybit')()
const BinanceBinanceLazyImport = createFileRoute('/binance/binance')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsSettingsLazyRoute = SettingsSettingsLazyImport.update({
  path: '/settings/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/settings.lazy').then((d) => d.Route),
)

const BybitBybitLazyRoute = BybitBybitLazyImport.update({
  path: '/bybit/bybit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bybit/bybit.lazy').then((d) => d.Route))

const BinanceBinanceLazyRoute = BinanceBinanceLazyImport.update({
  path: '/binance/binance',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/binance/binance.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/binance/binance': {
      preLoaderRoute: typeof BinanceBinanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/bybit/bybit': {
      preLoaderRoute: typeof BybitBybitLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/settings': {
      preLoaderRoute: typeof SettingsSettingsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BinanceBinanceLazyRoute,
  BybitBybitLazyRoute,
  SettingsSettingsLazyRoute,
])

/* prettier-ignore-end */
